version: "3.9"

services:
  specserver:
    build:
      context: .
      dockerfile: datahandler.Dockerfile
    container_name: specserver
    ports:
      - "9876:9876"
    environment:
      POSTGRES_URL: database:5432
      POSTGRES_USER: api
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: sensor
      APP_PORT: 9876
    networks:
      - vnet1

networks:
  vnet1:
    external: true