# --- Build stage ---
FROM golang:1.21 AS build

WORKDIR /src

COPY datahandler_source ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o datahandler ./main.go


# --- Runtime stage ---
FROM redhat/ubi10-minimal:10.7

WORKDIR /interface

COPY --from=build /src/datahandler .

EXPOSE 8901

ENTRYPOINT ["./datahandler"]
