# --- Build stage ---
FROM golang:1.21 AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o specserver ./main.go


# --- Runtime stage ---
FROM redhat/ubi10-minimal:10.7

WORKDIR /interface

COPY --from=build /src/specserver .

EXPOSE 8080

ENTRYPOINT ["./specserver"]
